// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVLj330X_SYTG7c_ufxG0NWq6gl8yDM74',
    appId: '1:97481477443:web:aa79d111e9c1ef7a8933f6',
    messagingSenderId: '97481477443',
    projectId: 'breathe-and-heal-c42c6',
    authDomain: 'breathe-and-heal-c42c6.firebaseapp.com',
    storageBucket: 'breathe-and-heal-c42c6.appspot.com',
    measurementId: 'G-D7NSKYSBZS',
    databaseURL: 'https://Breathe_and_heal.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyC_28lLWnP0rDU4QnsF6YOxqtSnQSh3pKg',
      appId: '1:97481477443:android:0f3ffa6dfa24dcde8933f6',
      messagingSenderId: '97481477443',
      projectId: 'breathe-and-heal-c42c6',
      storageBucket: 'breathe-and-heal-c42c6.appspot.com',
      databaseURL: 'https://Breathe_and_heal.firebaseio.com');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ5sVNJKK2GOKclZTcbf3rfO-6DAtEsow',
    appId: '1:97481477443:ios:c4d1e4d234b870f88933f6',
    messagingSenderId: '97481477443',
    projectId: 'breathe-and-heal-c42c6',
    storageBucket: 'breathe-and-heal-c42c6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1Test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ5sVNJKK2GOKclZTcbf3rfO-6DAtEsow',
    appId: '1:97481477443:ios:0eae753ad1996e3a8933f6',
    messagingSenderId: '97481477443',
    projectId: 'breathe-and-heal-c42c6',
    storageBucket: 'breathe-and-heal-c42c6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1Test.RunnerTests',
  );
}
